name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --locked --quiet

      - name: Package
        shell: pwsh
        run: |
          Compress-Archive `
            target/release/pitruck.exe `
            pitruck-windows.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: pitruck-windows.zip
